/**
 * MapLibre style builder.
 *
 * Builds a Protomaps basemap style backed by a per-region PMTiles
 * archive served through the `pmtiles://` MapLibre protocol. Layers are
 * generated by `@protomaps/basemaps` so there's no remote style fetch
 * — fast cold start, works fully offline once the PMTiles file is on
 * disk.
 *
 * Diverges from flight-planner: that plugin uses a single global
 * "daily planet" PMTiles served over HTTPS. atlas-maps targets
 * per-region local PMTiles built by planetiler during region install
 * (slice 6). The protocol handler will receive the vault-relative path
 * and use `api.vault.readFileBytes` to do range reads — see
 * `cached-pmtiles-protocol.ts` (lands with slice 2b / slice 6).
 *
 * Theme resolution priority:
 *   1. `<html class="dark">` — Knosys ThemeProvider's explicit dark.
 *   2. `<html data-theme="..." >` — host's declared mode.
 *   3. `prefers-color-scheme: dark` — OS fallback for when the plugin
 *      runs outside Knosys.
 */

import { layers, namedFlavor } from '@protomaps/basemaps'
import type { StyleSpecification } from 'maplibre-gl'
import { MAP_ATTRIBUTION } from '@/constants'

export type MapTheme = 'light' | 'dark'

/** Protomaps hosts the glyphs + sprite assets used by the basemap
 *  flavors. These remain over HTTPS because they're small + cached by
 *  the browser, and bundling them into the plugin would push the
 *  distribution past the user-friendly size budget. */
const GLYPHS_URL =
  'https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf'

function spriteUrl(theme: MapTheme): string {
  return `https://protomaps.github.io/basemaps-assets/sprites/v4/${theme}`
}

export function currentMapTheme(): MapTheme {
  if (typeof document !== 'undefined') {
    const html = document.documentElement
    if (html.classList.contains('dark')) return 'dark'
    const attr = html.getAttribute('data-theme')
    if (attr === 'dark') return 'dark'
    if (attr === 'light') return 'light'
  }
  if (typeof window !== 'undefined' && window.matchMedia) {
    return window.matchMedia('(prefers-color-scheme: dark)').matches
      ? 'dark'
      : 'light'
  }
  return 'light'
}

/**
 * Build a MapLibre style for a per-region PMTiles archive at
 * `pmtilesUrl` (passed through to the registered protocol handler).
 *
 * Pass `null` when no region is active — returns an empty style so the
 * map canvas mounts without rendering vector layers. The chrome stays
 * visible against the host background; the zero-state UI sits over it.
 */
export function buildPlanetStyle(
  pmtilesUrl: string | null,
  theme: MapTheme = 'light',
): StyleSpecification {
  if (!pmtilesUrl) {
    // No region active: empty style. MapLibre will render an empty
    // canvas (no tiles, no layers), and the EmptyState overlay covers
    // it with the install-a-region affordance.
    return {
      version: 8,
      sources: {},
      layers: [],
    } as StyleSpecification
  }

  return {
    version: 8,
    glyphs: GLYPHS_URL,
    sprite: spriteUrl(theme),
    sources: {
      protomaps: {
        type: 'vector',
        url: `pmtiles://${pmtilesUrl}`,
        attribution: MAP_ATTRIBUTION,
      },
    },
    layers: layers('protomaps', namedFlavor(theme), { lang: 'en' }),
  } as StyleSpecification
}
